/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    testImplementation("junit:junit:4.13")
}

tasks.withType<Test>().configureEach {
    testLogging {
        showStackTraces = true
        showStandardStreams = true
    }
}
